# Generated by Django 5.2 on 2025-04-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Individu", "Individu"),
                            ("Entreprise", "Entreprise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_tel", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("adresse", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("materiel", "Materiel"),
                            ("entertainment", "Entertainment"),
                            ("Food", "Food"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_tel", models.BigIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("adresse", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_evenement", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Mariage", "Mariage"),
                            ("Party", "Party"),
                            ("Conference", "Conference"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_contrat", models.DateField()),
                ("status", models.CharField(max_length=100)),
                (
                    "Progress",
                    models.DecimalField(decimal_places=2, default="0.0", max_digits=5),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ses_clients",
                        to="eventApp.client",
                    ),
                ),
                (
                    "fournisseurs",
                    models.ManyToManyField(
                        related_name="ses_fournisseurs", to="eventApp.fournisseur"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Espece", "Espece"),
                            ("Cheque", "Cheque"),
                            ("Virement", "Virement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_paiement", models.DateField()),
                ("montant", models.FloatField()),
                ("reste", models.FloatField()),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to="eventApp.client",
                    ),
                ),
                (
                    "evenement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ses_paiements",
                        to="eventApp.evenement",
                    ),
                ),
            ],
        ),
    ]
