# Generated by Django 5.2 on 2025-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
