# Generated by Django 5.2 on 2025-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventApp", "0002_client_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="client_images/"),
        ),
    ]
