# Generated by Django 5.2 on 2025-04-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventApp", "0004_paiement_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="deleted",
            field=models.BooleanField(default=True),
        ),
    ]
