# Generated by Django 5.2 on 2025-04-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventApp", "0005_evenement_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenement",
            name="deleted",
        ),
    ]
