# Generated by Django 5.2 on 2025-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventApp", "0007_evenement_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="fournisseur",
            name="deleted",
            field=models.BooleanField(default=True),
        ),
    ]
