# Generated by Django 5.2 on 2025-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventApp", "0008_fournisseur_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fournisseur",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
