# Generated by Django 5.2 on 2025-04-29 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventApp", "0009_alter_fournisseur_deleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ressource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("Materiel", "Materiel"), ("Food", "Food")],
                        max_length=50,
                    ),
                ),
                ("quantite_disponible", models.PositiveIntegerField(default=1)),
                (
                    "cout_unitaire",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("disponible", models.BooleanField(default=True)),
                ("returned", models.BooleanField(default=False)),
                ("date_acquisition", models.DateField(blank=True, null=True)),
                ("damaged", models.PositiveIntegerField(default=0)),
                (
                    "evenement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ressources",
                        to="eventApp.evenement",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ressources",
                        to="eventApp.fournisseur",
                    ),
                ),
            ],
        ),
    ]
